python main.py \
	--mode test_render \
	--env Carla-v0 \
	--image-size 256 512 \
	--gpu 0 --sampler-gpu 1 \
	--image-size 256 512 \
	--n-past-actions 10 \
	--hidden-dims 256 128 \
	--activation LeakyReLU \
	--encoder-arch BETAVAE \
	--state-dim 512 \
	--max-episode-steps 5000 \
	--random-seed 49 \
	--record-video \
	--load-checkpoint \
	--dry-run-init-env \
	--weight-path "vae_weights/Carla-v0_town7/bvae_town7_epoch(100)-loss(+2.489E+05).pkl" \
	--log-dir "logs/Carla-v0_town7_test_render/BETAVAE" \
	--checkpoint-dir "savedcheckpoints/Carla-v0/BETAVAE"
