python main.py \
	--mode test_render \
	--env Carla-v0 \
	--gpu 1 \
	--n-past-actions 10 \
	--hidden-dims 256 128 \
	--activation LeakyReLU \
	--encoder-arch VAE \
	--state-dim 512 \
	--max-episode-steps 5000 \
	--random-seed 49 \
	--record-video \
	--load-checkpoint \
	--dry-run-init-env \
	--weight-path "/root/thesis/thesis-code/Soft-Actor-Critic/vae_weights/Carla-v0_town7_outskirts_b3/bvae_town7_epoch(100)-loss(+2.453E+05).pkl" \
	--log-dir "logs/Carla-v0_town7_test_render/VAE" \
	--checkpoint-dir "savedcheckpoints/Carla-v0/VAE"
